language: node_js
branches:
  only:
    - master
    - refactall
    - /^greenkeeper/.*$/
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - node
before_script:
  - npm install -g browserstack-runner
script:
  - npm run test:prod && npm run build
  - browserstack-runner
after_success:
  - npm run report-coverage
  - npm run deploy-docs
  - npm run semantic-release
